on: 
  push: 
    branches: 
      - master

name: Build and Publish
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'no-ci')"
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 20.12.1
      uses: actions/setup-node@v1
      with:
        node-version: 20.12.1
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install Dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: Deploy to NPM! 🚀
      uses: Github-Actions-Community/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
